version: '3.7'

networks:
  creative:
    ipam:
      config:
        - subnet: 172.27.0.0/16

services:
  app:
    build:
      dockerfile: docker/php-dev.Dockerfile
      context: .
    volumes:
      - .:/var/www/app
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: 'dev'
    links:
      - database
    networks:
      - creative

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      creative:
        ipv4_address: 172.27.0.2

  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/app
      - ${DOCUMENT_ROOT-./docker/nginx/conf.d}:/etc/nginx/conf.d
    links:
      - app
    networks:
      - creative
