main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  construct: [ Slim\Interfaces\RouteCollectorInterface, Twig\Environment, Doctrine\ORM\EntityManagerInterface ]
  action: index

info:
  method: 'get'
  path: info/{id}
  controller: App\Controller\HomeController
  action: info

